Bump required Python 3.7 -> 3.8
rwth-i6/returnn pull request #1668
Opened 2024-12-13 10:51 UTC by NeoLegends

Closes #1326

Opening this to run CI and such.

2024-12-13 11:07 UTC, NeoLegends commented
By dropping support for 3.7 we also drop support for TF1.

It is my understanding that some folks might still be using TF1.x for some of their experiments. However, these experiments are probably also using ancient RETURNN versions, so I believe it's ok to drop support.

2024-12-13 11:11 UTC, albertz requested changes

2024-12-13 11:11 UTC, albertz commented on CHANGELOG.md
> +## 2023-12-13: Bump min Python version from 3.7 to 3.8 ([issue #1326](https://github.com/rwth-i6/returnn/issues/1326))
2024

2024-12-13 11:13 UTC, albertz commented
Can you also add a line to our readme (or where else do you think we should put it)?

2024-12-13 12:26 UTC, albertz commented on .github/workflows/main.yml
> -            tf-version: 1.15.3
Why did you remove this?

2024-12-13 12:26 UTC, albertz commented on .github/workflows/main.yml
> +        if [[ "${{matrix.tf-version}}" == 2.[0123].* ]]; then
Why?

2024-12-13 12:26 UTC, albertz commented on CHANGELOG.md
> +This also drops support for TF 1.x.
Why?

2024-12-13 12:28 UTC, NeoLegends commented
> Why?

TF1 never supported Python > 3.7. See the CI log. There are no pip packages available for TF1 for 3.8 and onwards.

2024-12-13 12:30 UTC, albertz commented
Please check with @curufinwe if dropping TF1 is ok.

2024-12-13 12:42 UTC, albertz commented on README.rst
> +pip dependencies are listed in ``requirements.txt`` and ``requirements-dev``, although some parts of the code may require additional dependencies (e.g. ``librosa``, ``resampy``) on-demand.
```suggestion
Pip dependencies are listed in ``requirements.txt`` and ``requirements-dev``,
although some parts of the code may require additional dependencies (e.g. ``librosa``, ``resampy``) on-demand.

For TensorFlow-based setups, RETURNN requires TF >=2.

For PyTorch-based setups, RETURNN requires Torch >=1.
```
(I actually don't really know our min required Torch version... But this here would be some good starting point.)

2024-12-13 12:44 UTC, albertz commented
In the failing test, can you filter out `[IWE] tensorflow/` from stdout? I think that should fix the test.

2024-12-13 14:30 UTC, albertz commented
Ah, in the failing test checking the stdout, the `SyntaxWarning`s are also new. Let's either fix the syntax warning or filter those out as well.

2024-12-17 11:24 UTC, albertz approved these changes

2024-12-17 11:25 UTC, merged